# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
#    routing_loader: true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            path: '^/'
            priorities: ['json']
            fallback_format: 'json'
            prefer_extension: false
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations
    view:
        formats: 
            json: true
            xml: false
            rss: false
        view_response_listener:  true
    serializer:
        serialize_null: false
    exception:
        enabled: true
        codes:
            App\Exception\ResourceValidationException: 400
        messages:
            App\Exception\ResourceValidationException: true
        exception_controller: 'fos_rest.exception.controller:showAction'