0:
    name: "CAT Smartphone 4g outdoor 11.9 cm (4.7 pouces) s60 32 go noir"
    model: "CAT 4g s60"
    description: "Le nouveau Cat S60 avec caméra thermique intégrée de FLIR, leader mondial dans le secteur des technologies à imagerie thermique, offre pour la première fois à l’utilisateur une multitude de possibilités d’utilisation qui sont tout à fait uniques à ce jour pour les smartphones. Ainsi, il permet entre autres de détecter les fuites de chaleur autour des portes et fenêtres mal isolées et l'émergence de zones humides en raison du manque d'isolation ou même le risque de surchauffe des appareils et des circuits électriques. C’est pourquoi le nouveau Cat S60 est parfait pour les électriciens, les artisans, les services de secours ainsi que les employés des fournisseurs d’énergie ou dans d’autres secteurs..."
    manufacturer: "CAT"
    stock: 10
    priceHT: 1615.99
    pictures:
        [
            "https://image.darty.com/darty?type=image&source=/market/2018/04/09/mkp_wnezb4Im6c8KMA.jpeg&width=400&height=300&quality=70",
        ]
1:
    name: "Huawei mate 9 porsche design 256go dual sim débloqué - graphite noir"
    model: "Huawei mate 9 porsche design"
    description: "Inspiré par leur passion éternelle pour la performance, Huawei a introduit le monde à leur dernier téléphone haut de gamme - Mate Huawei 9 Porsche. Doté d'un design Porsche élégant et stylé, ce smartphone complet noir est certainement un régal pour les yeux. Mate Porsche Design Huawei 9 est livré avec la technologie state-of-the art - lui permettant de produire une performance extrêmement puissant et ultra-rapide tout comme une voiture Porsche lui-même. Avec ses caractéristiques haut de gamme et desigh étonnante, ce téléphone Android est vraiment un dispositif haute performance de luxe qui est adapte le style de quelqu'un qui aime pousser la vie à la limite."
    manufacturer: "Huawei"
    stock: 40
    priceHT: 1870.00
    pictures:
        [
            "https://image.darty.com/darty?type=image&source=/market/2018/04/11/mkp_RABQhHfsQ0qfKA.jpeg&width=300&height=400&quality=70",
        ]
2:
    name: " Xiaomi 4g 5.5 pouces mi a1 64 go rouge"
    model: "Xiaomi mi A1"
    description: "Caractéristiques techniques Catégorie Smartphone 4G Système d'exploitation Android™ 7.1 Nougat Processeur/ Type Octa Core Processeur / Nombre de cœurs 8 x Cadence de traitement du processeur 2 GHz Écran (cm) 14 cm Écran (pouces) 5.5 pouces Résolution écran 1920 x 1080 pix Mode de résolution d'affichage Full HD Resolution of integrated camera 12 MPix, 12 MPix Résolution de la caméra frontale 5 MPix Capacité mémoire 64 Go Slot pour cartes mémoire Carte microSD (128 Go max.)..."
    manufacturer: "Xiaomi"
    stock: 10
    priceHT: 1160.00
    pictures:
        [
            "https://image.darty.com/darty?type=image&source=/market/2018/04/09/mkp_YG1iELdpwowa1w.jpeg&width=400&height=300&quality=70",
        ]
3:
    name: "Cyrus 4g outdoor 11.9 cm (4.7 pouces) cs27 8 go noir"
    model: "Cyrus 4g outdoor cs27"
    description: "Huawai P8 Lite version 2017 toujours aussi rapide et puissant dans un tout nouveau design. Découvrez le  Huawei  P8 Lite nouvelle version, habillé tout de verre, il vous offre de nouvelles sensations. Grâce à ses courbes soignées, ses  7.6 mm d’épaisseur, et son écran parcourant la quasi intégralité de la face du téléphone, le P8 Lite 2017 se logera parfaitement dans le creux de votre main. Toujours à la pointe de la technologie avec son processeur huit coeurs, ses 3 Go de Ram et sa compatibilité 4G."
    manufacturer: "Cyrus"
    stock: 60
    priceHT: 1038.00
    pictures:
        [
            "https://image.darty.com/darty?type=image&source=/market/2018/04/09/mkp_E-PCLbfZw8yN2w.jpeg&width=400&height=300&quality=70",
        ]
4:
    name: "Dok Phone razer"
    model: "Dok Phone razer"
    description: "Offrez-vous la meilleure expérience gaming sur portable grâce au Razer Phone ! Ce smartphone est le premier au monde à disposer d'un écran 5.7\" 120 Hz afin de vous faire profiter d'un contenu ultra fluide pour tous vos jeux. De plus, grâce à la technologie UltraMotion et à la réponse tactile précise, vous ne souffrirez d'aucune latence ou de saccades. Il est accompagné également par un processeur Qualcomm Snapdragon 835 Octo-Core cadencé à 2.35 GHz, 8 Go de RAM et une capacité de stockage de 64 Go."
    manufacturer: "RAZER"
    stock: 90
    priceHT: 1079.99
    pictures:
        [
            "https://image.darty.com/darty?type=image&source=/market/2018/04/13/mkp_LYsSPRVg1sFfug.jpeg&width=400&height=300&quality=70",
            "https://image.darty.com/darty?type=image&source=/market/2018/04/13/mkp_NMoEpwmY9lT1dg.jpeg&width=400&height=300&quality=70",
            "https://image.darty.com/darty?type=image&source=/market/2018/04/13/mkp_U2mwS6vnmTA6Vg.jpeg&width=400&height=300&quality=70",
        ]
5:
    name: "Huawei Y6 Pro 2017"
    model: "Huawei Y6 Pro 2017"
    description: "Découvrez le Y6 Pro 2017 de chez Huawei : La parfaite adéquation d'un design élégant et d'une finesse incroyable, couplé à des performances puissantes qui répondront à tous vos besoins du quotidien n'importe où et à n'importe quel moment ! Son écran HD de 5\" d'une résolution de 1280 x 720 pixels offre à son utilisateur une expérience visuelle agréable dans n'importe quelle situation ! Ses performances puissantes de son processeur Quad-Core, d'un réseau 4G et 2 Go de mémoire RAM assurent une fluidité du système même avec plusieurs applications ouvertes en même temps 7!"
    manufacturer: "Huawei"
    stock: 50
    priceHT: 179.99
    pictures:
        [
            "https://image.darty.com/gps_communication/telephone_mobile/telephone_portable/huawei_y6_pro_17_gold_t1708234347641A_110511271.jpg",
        ]
6:
    name: "Samsung Galaxy S7 Edge"
    model: "Samsung Galaxy S7 Edge"
    description: "Le  design gracieux du  Galaxy S7 EDGE est le résultat d'une longue recherche et d'un développement méticuleux. Habillé de verre et de métal et offrant des courbes parfaites, le Galaxy S7 EDGE a été conçu avec soin pour un résultat extraordinaire. Parce que la beauté ne fait pas tout,le Galaxy S7 Edge est un concentré des dernières technologies : son interface pensée pour une utilisation intuitive et optimale vous permet de profiter de performances inégalées."
    manufacturer: "Samsung"
    stock: 100
    priceHT: 699.99
    pictures:
        [
            "https://image.darty.com/gps_communication/telephone_mobile/telephone_portable/samsung_galaxy_s7edge_ble_t1702024286693A_165519522.jpg",
            "https://image.darty.com/gps_communication/telephone_mobile/telephone_portable/samsung_galaxy_s7edge_ble_t1702024286693C_165517537.jpg",
            "https://image.darty.com/gps_communication/telephone_mobile/telephone_portable/samsung_galaxy_s7edge_ble_t1702024286693D_165516586.jpg",
        ]
7:
    name: "Huawei P20 BLACK 128GO"
    model: "Huawei P20 BLACK"
    description: "Le nouveau P20 de chez Huawei: un smartphone au design compact et élégant !  Son  écran 14,7 cm (5,8\") Full HD+ d'une résolution de 2240 x 1080 pixels   apporte un vent de fraîcheur grâce à des couleurs nettes et profondes ! Ses performances puissantes dû  à  son processeur Octo-Core, d'un réseau 4G+ et de 4 Go Ram , il offre une fluidité du système sans interruption même avec plusieurs applications ouvertes en même temps !"
    manufacturer: "Huawei"
    stock: 100
    priceHT: 699.99
    pictures:
        [
            "https://image.darty.com/gps_communication/telephone_mobile/telephone_portable/huawei_p20_black_128go_t1803264399854A_171556317.jpg",
            "https://image.darty.com/gps_communication/telephone_mobile/telephone_portable/huawei_p20_black_128go_t1803264399854C_171550812.jpg",
        ]
8:
    name: "Apple IPHONE X 64 GO GRIS SIDERAL"
    model: "Apple IPHONE X"
    description: " Nous avons toujours rêvé de créer un iPhone qui ne soit qu’écran. Un iPhone si immersif qu’il s’efface au profit de la seule expérience. Un iPhone si intelligent qu’il réponde à un geste, à la voix… et même à un regard. C’est chose faite aujourd’hui. Dites bonjour au futur. Comment créer un appareil supérieurement intelligent dont le boîtier et l’écran fusionnent en un seul et même bloc homogène ? C’est l’objectif que nous nous étions fixé dès la conception du premier iPhone. Et c’est ce que nous avons accompli avec l’iPhone X."
    manufacturer: "Apple"
    stock: 10
    priceHT: 1159.99
    pictures:
        [
            "https://image.darty.com/telephonie/telephone_mobile_seul/iphone/apple_iph_x_64g_sg_d1710124368355A_163407290.jpg",
            "https://image.darty.com/telephonie/telephone_mobile_seul/iphone/apple_iph_x_64g_sg_s1710124368355B_163405753.jpg",
        ]
9:
    name: "Apple IPHONE 8 256 GO GRIS SIDERAL"
    model: "Apple IPHONE 8"
    description: "Un nouveau design tout de verre vêtu. L’appareil photo le plus populaire au monde, encore amélioré. La plus puissante et la plus intelligente des puces de smartphone. Le chargement sans fil et sans effort. Et des expériences de réalité augmentée inimaginables auparavant. Voici l’iPhone 8. Une nouvelle génération d’iPhone."
    manufacturer: "Apple"
    stock: 55
    priceHT: 979.99
    pictures:
        [
            "https://image.darty.com/telephonie/telephone_mobile_seul/iphone/apple_iph8_64gb_sg_t1709154360940A_173551648.jpg",
            "https://image.darty.com/telephonie/telephone_mobile_seul/iphone/apple_iph8_64gb_sg_t1709154360940B_173548710.jpg",
        ]
10:
    name: "Google pixel 2 xl 128go débloqué - noir"
    model: "Google pixel 2"
    description: "Découvrez une meilleure façon de capturer, stocker et voir le monde. Pixel 2 XL dispose d'une caméra intelligente qui prend de belles photos dans n'importe quelle lumière, une batterie à charge rapide et l'Assistant Google intégré."
    manufacturer: "Google"
    stock: 2
    priceHT: 1049.00
    pictures:
        [
            "https://image.darty.com/darty?type=image&source=/market/2018/04/11/mkp_T0IyQkhF8AhfVQ.jpeg&width=300&height=400&quality=70",
            "https://image.darty.com/darty?type=image&source=/market/2018/04/11/mkp_HItTFF25KAp1RA.jpeg&width=400&height=300&quality=70",
        ]
11:
    name: "Samsung GALAXY NOTE 8 OR"
    model: "Samsung GALAXY NOTE 8"
    description: "Découvrez une meilleure façon de capturer, stocker et voir le monde. Pixel 2 XL dispose d'une caméra intelligente qui prend de belles photos dans n'importe quelle lumière, une batterie à charge rapide et l'Assistant Google intégré."
    manufacturer: "Samsung"
    stock: 12
    priceHT: 1009.00
    pictures:
        [
            "https://image.darty.com/gps_communication/telephone_mobile/telephone_portable/samsung_great_2_g_t1708234351908A_150958814.jpg",
            "https://image.darty.com/gps_communication/telephone_mobile/telephone_portable/samsung_great_2_g_t1708234351908B_150957835.jpg",
            "https://image.darty.com/gps_communication/telephone_mobile/telephone_portable/samsung_great_2_g_t1708234351908D_150955770.jpg",
        ]